name: Publish Demo Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Testes
        run: |
          echo Testes Running
          echo Testes passing
      
      - name: Build aplication
        run: echo Build aplication

  deloyment-develop:
    needs: [build]
    environment: desenvolvimento
    runs-on: ubuntu-latest
    steps:
      - name: deploy to develop
        run: echo deploy develop

  generate-artefates:
    runs-on: macOS:latest
    steps:
      - name: Build Artefactory
        run: echo Build artefactory
        
      - name: Download Artefactory
        run: echo Download artefactory
    
  
